spring.application.name=UFMAExtensao

# Datasource - PostgreSQL Supabase
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.iuxuvypvusxwfvzanapt
spring.datasource.password=24680Stardustdragon!

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Garante que o data.sql rode DEPOIS do JPA criar as tabelas
# spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never