spring.application.name=UFMAExtensao

# Datasource - SQLite
spring.datasource.url=jdbc:sqlite:ufmaextensao.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Garante que o data.sql rode DEPOIS do JPA criar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always